[formatting]
# Align with prettier: 2-space indent, 80-col width
indent_string = "  "
column_width = 80
trailing_newline = true
crlf = false

# Array formatting
array_trailing_comma = true
array_auto_expand = true
array_auto_collapse = true
compact_arrays = true

# Table formatting
compact_inline_tables = false
reorder_keys = false
